### ISSUE TITLE
craft crafting table if one exists already

### ISSUE THREAD

**Issue by wshadow** [andrewminer/crafting-guide#114]
Following the link you left on the Railcraft issue tracker http://crafting-guide.com/craft/16.minecart:2.item_loader:locking_track:64.track I added a crafting table under the section "Items you have", but Step 2 of 37 tells me to craft a crafting table. This step is removed if I claim to have a second crafting table available.

**Comment by andrewminer** [comment]
I believe that's happening because you turned on the "including tools" checkbox.  This tells Crafting Guide that you always want instructions and requirements for building all the tools required at each step (e.g., crafting tables, furnaces, and the like).  In this case, you need two crafting tables because one of them is consumed in making the Rolling Machine, and you need the other one for making items.
