### ISSUE TITLE
Unable to Add Specific Enchanted Book to Recipe Input

### ISSUE THREAD

**Issue by spaz926** [andrewminer/crafting-guide#297]
When attempting to add support for a new modpack, I am unable to add a few recipes due to lack of support for specific enchanted books. The vanilla item list contains only an entry for gatherable enchanted book, not specific enchanted books (protection, efficiency, etc.)

Is there a workaround or should enchantment types be added as supported?

**Comment by andrewminer** [comment]
The process I use for automatically exporting items doesn't capture the various kinds of enchanted books.  Feel free, though, to add them to the vanilla Minecraft file.  Be sure to re-run the `compile-json-modpack-archive` before testing so that your local version of the site gets those new recipes.
