### ISSUE TITLE
I tried sending feedback, but all I get is "sending failed. Please try again."

### ISSUE THREAD

**Issue by macks2008public** [andrewminer/crafting-guide#321]
Name used: "macks2008"
Email used: <same as this account's verified email>
Comment: "I came to this site trying to remember an alternate recipe for this item (in case context is not included with this feedback, I'm making this comment on the enhanced_energy_conduit entry) that became available in more recent versions, but your site only seems to support one recipe per item. The alternate recipe I was looking for involved a normal energy conduit, and allowed the player to upgrade it for slightly less energetic alloy than crafting it directly. Any idea what the recipe was?"

**Comment by andrewminer** [comment]
Thanks for letting me know about the broken feedback link... obviously, it's one of those things which is harder than usual for people to let me know about!

I'm afraid it's been a very long while since I've had the time or interest to update Crafting Guide, so the data is now quite old.  I suspect you'd do better checking out the official [ThermalFoundation](http://teamcofh.com/docs/thermal-foundation/) documentation to see if it has what you're looking for.  Although, for recipes, you'd generally do best to install [JustEnoughItems](https://minecraft.curseforge.com/projects/jei) in your modpack and looking in there.

**Comment by macks2008public** [comment]
I understand if the data is out of date; it's a lot of stuff to keep track of and up-to-date. Have you considered turning the project into a sort of "how do I craft this again" wiki? It seems like you're halfway there, and it would allow other people to keep stuff up to date. Granted, there's already [a wiki](ftb.gamepedia.com) that tries to do that (and more), but maybe a GUI-based crafting wiki would be able to do it better than one focused on a more general "all the information" purpose.
And yes, I'm aware of JEI; I just didn't feel like starting up the 1.10 pack on which I have it installed when all I wanted to do was back-port some recipes using minetweaker. I did eventually end up doing that anyway, but only when I realized your data was outdated and not going to help me.
