### ISSUE TITLE
Add support for Forestry (+6)

### ISSUE THREAD

**Issue by andrewminer** [andrewminer/crafting-guide#55]
URL: http://forestry.sengir.net/wiki.new/doku.php

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
@sheldongriffin is working on this

**Comment by sheldongriffin** [comment]
And this is as good an impetus as any for me to get it finished!

That being said, there are issues that I'm not sure the back-end can currently handle, with recipes that take more than a 3x3 grid. Take the electron tube recipe, for example, from this page http://forestry.sengir.net/wiki.new/doku.php?id=crafting:fabricator . Admittedly, in that case, I could put the glass in the 3x3, since it's not actually full, but that would be confusing and undoubtedly there are mods with the full 9 slots taken that still require other ingredients.

If there's a way that we can account for those extra pieces, please point it out, otherwise we'll just have to accept a certain amount of missed items.

**Comment by andrewminer** [comment]
Hmm.  Good question.  There are a bunch of machines which don't use a 3x3 grid (e.g., the lowly furnace), but all the one's I've dealt with so far at least fit reasonably well within the 3x3 grid.

For now, I'd say: just add the recipe ignoring the sand/glass.  Folks who know enough to use the Thermionic Fabricator will probably know about it's requirement for sand/glass, just as they know about its requirement for energy (which also isn't included in Crafting Guide, but should be).

I'll make a note in issue #48 to make sure to deal with these recipes.

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
+1 via feedback form

**Comment by andrewminer** [comment]
FYI—I'm moving all my issues over to [Trello](https://trello.com/b/s9N0aTYd/crafting-guide), so don't worry that this issue is getting closed.  Forestry is very much still in demand!

**Comment by sheldongriffin** [comment]
It is basically done, but work is pushing it to the side. All the recipes are in, minus some "do the same with 20 different wood types".. I'm just at the stage of double checking. So if it takes too long you may want to check what's already checked in.
